version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: javaee-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javaee_db
      MYSQL_USER: javaee
      MYSQL_PASSWORD: javaee
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
